# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t api`.
FROM public.ecr.aws/docker/library/node:20-bookworm

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

COPY package.json /app
RUN npm install
COPY . /app
RUN apt-get update -y && apt-get install -y openssl
RUN npx prisma generate
RUN npm run build

CMD ["npm","run", "start"]